wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1661948395.125193
    t:
      1:
      - 1
      - 9
      - 55
      - 77
      2:
      - 1
      - 9
      - 55
      - 77
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.13.2
      8:
      - 2
      - 5
dataset:
  desc: null
  value: Cora
